### ISSUE TITLE
Implementation of Delay

### ISSUE THREAD

**Issue by stephan-1975** [Exim/exim#27]
Hi folks (and thanks in advance for reading this),

I'm currently trying to implement a delay function into an exim4 mta. It is running in the hand-on-to-smarthost mode. I'd like to add a delay to every e-mail that is handed to the mta locally before it is forwarded onto the internet.

What I've tried: I've added "delay = 20s" to the final "accept" statements in the acl-files that rest in /etc/exim4/conf.d/acl . Usually that should do, but unfortunately I can't see any change.

First of all, if I log onto the mailserver using telnet, there should be a delay, but there's nothing.

Any help is appreciated!

Thank you for your efforts in advance!

Stephan

**Comment by jamieabbott** [comment]
Hi Stephan,

Just a thought, could you not delay instant sending of all emails and merely add them to the queue?  That would then allow them to be processed every minute or so?

Jamie

**Comment by stephan-1975** [comment]
Hi Jamie,

thanks for the thought. Sounds good but I don't have a clue how to 
configure that. Does that mean that the mails that arrive at the 
exim-Server are accepted, pushed into the queue and then - after a 
minute - everything in the queue is processed? That would mean that 
after one minute there could be 10 or 20 e-mails in the queue and then 
be sent out - but that's something my isp doesn't like at all. Too many 
mails ariving at the mta of my isp at a time means they're recognised as 
spam.

Stephan

Am 15.01.2015 um 09:24 schrieb jamieabbott:

**Comment by philpennock** [comment]
Before trying to answer the specifics, to try to help you better in future: we don't normally do support/help in GitHub issues, but that's mostly a "we're an older project with established practices which are only slowly changing" issue; also, though, we're volunteer-based and most help comes from the large pool of volunteers who are postmasters but not developers, over on the mailing-lists.

In this case, the `conf.d` system you're using is part of the Debian packaging of Exim, rather than part of Exim itself: we ship with one single flat-file heavily-commented configuration file (which you can find in `/usr/share/doc/exim4/examples/example.conf.gz`

I suspect that there's some kind of Debian-ist `dpkg-reconfigure` which you need to run, so that your changes are picked up and put into the configuration file used by Exim, which you can see stated when you run `exim --version`
